<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="75923" started-at="2019-03-15T22:42:46Z" finished-at="2019-03-15T22:44:02Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="75923" started-at="2019-03-15T22:42:46Z" finished-at="2019-03-15T22:44:02Z">
      <class name="com.virtusa.cdhtest.Dbchecktest">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:com.virtusa.cdhtest.Dbchecktest@3108bc]" name="beforeTest" is-config="true" duration-ms="10" started-at="2019-03-15T18:42:46Z" finished-at="2019-03-15T18:42:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="FAIL" signature="dbcheck()[pri:0, instance:com.virtusa.cdhtest.Dbchecktest@3108bc]" name="dbcheck" duration-ms="75887" started-at="2019-03-15T18:42:46Z" finished-at="2019-03-15T18:44:02Z">
          <exception class="java.sql.SQLException">
            <message>
              <![CDATA[Could not open connection to jdbc:hive2://192.168.1.227:10000/default: java.net.ConnectException: Operation timed out (Connection timed out)]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.sql.SQLException: Could not open connection to jdbc:hive2://192.168.1.227:10000/default: java.net.ConnectException: Operation timed out (Connection timed out)
	at org.apache.hive.jdbc.HiveConnection.openTransport(HiveConnection.java:187)
	at org.apache.hive.jdbc.HiveConnection.<init>(HiveConnection.java:164)
	at org.apache.hive.jdbc.HiveDriver.connect(HiveDriver.java:105)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.virtusa.cdhtest.ClouderaHiveJdbcTest.runQuery(ClouderaHiveJdbcTest.java:94)
	at com.virtusa.cdhtest.Dbchecktest.dbcheck(Dbchecktest.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: org.apache.thrift.transport.TTransportException: java.net.ConnectException: Operation timed out (Connection timed out)
	at org.apache.thrift.transport.TSocket.open(TSocket.java:185)
	at org.apache.thrift.transport.TSaslTransport.open(TSaslTransport.java:248)
	at org.apache.thrift.transport.TSaslClientTransport.open(TSaslClientTransport.java:37)
	at org.apache.hive.jdbc.HiveConnection.openTransport(HiveConnection.java:185)
	... 30 more
Caused by: java.net.ConnectException: Operation timed out (Connection timed out)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.thrift.transport.TSocket.open(TSocket.java:180)
	... 33 more
]]>
            </full-stacktrace>
          </exception> <!-- java.sql.SQLException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dbcheck -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:com.virtusa.cdhtest.Dbchecktest@3108bc]" name="afterTest" is-config="true" duration-ms="0" started-at="2019-03-15T18:44:02Z" finished-at="2019-03-15T18:44:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- com.virtusa.cdhtest.Dbchecktest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
